"""The normalizer's field roster must agree with the schema.

`collection.schema.json` is generated by `hbt --schema` from the Rust
implementation and is the authority on field names and types.  `normalize.py`
restates the membership of its property lists, because it needs to partition
those fields by how each is normalized, and that partition is knowledge the
schema does not carry.

Restating them is fine; letting them drift is not.  Without this test, a field
added upstream would reach the harness as "unknown field(s) …" reported against
four conforming implementations, which reads as four parser bugs.  With it, the
same change is one red test in the repository that owns the specification.
"""

# Each test's name is its description; a docstring would restate it.
# pylint: disable=missing-function-docstring

from __future__ import annotations

import json
import unittest
from pathlib import Path
from typing import Any

# Imported from the module rather than the package: `hbt.conformance` also
# exports a function called `normalize`, which shadows the module of that name.
from hbt.conformance.normalize import COLLECTION_FIELDS, ENTITY_FIELDS, ENTITY_REQUIRED, NODE_FIELDS, SEMVER

SCHEMA_PATH = Path(__file__).resolve().parents[1] / "collection.schema.json"


def load_schema() -> dict[str, Any]:
    with SCHEMA_PATH.open(encoding="utf-8") as handle:
        loaded: dict[str, Any] = json.load(handle)
    return loaded


class SchemaAgreement(unittest.TestCase):
    def setUp(self) -> None:
        self.schema = load_schema()

    def test_the_collection_fields_are_the_schema_s(self) -> None:
        self.assertEqual(COLLECTION_FIELDS, frozenset(self.schema["properties"]))

    def test_the_node_fields_are_the_schema_s(self) -> None:
        self.assertEqual(NODE_FIELDS, frozenset(self.schema["$defs"]["NodeRepr"]["properties"]))

    def test_the_entity_fields_are_the_schema_s(self) -> None:
        self.assertEqual(ENTITY_FIELDS, frozenset(self.schema["$defs"]["Entity"]["properties"]))

    def test_the_semver_pattern_is_the_schema_s(self) -> None:
        self.assertEqual(SEMVER.pattern, self.schema["$defs"]["SemVer"]["pattern"])

    def test_every_required_field_the_normalizer_demands_is_required_upstream(self) -> None:
        """The converse does not hold, and deliberately so.

        The schema requires `updatedAt`, `names` and `labels`; the normalizer
        treats an absent list as empty, because the schema gives those fields
        `default: []` in the same breath. So the normalizer demands a subset.
        """
        self.assertLessEqual(
            set(ENTITY_REQUIRED),
            set(self.schema["$defs"]["Entity"]["required"]),
        )


if __name__ == "__main__":
    unittest.main()
